// Test validation (VALID ONE)
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwNzEyMzI5NDUsInJvbGUiOiJST0xFX0FETUlOIiwidXNlciI6ImFkbWluIn0.ukOiJTR7Xvv9o4RFYKTMTqicSjrpNikJ7zvX3vjZD8Aqy3Y2dgGO1L-J0Y2k9S5p9PmP-FZMB0ViU93bli2XA1A7sPUVoWYGMEyTw-k-zUWn_4jVR8LT3yx-d0wwVsbpx3zNBxtTKPYykshJ9sy1m950Hz20202j9ZnbBo2BRezq8sLpLFA_JhO9xLpAGtnTLdkFl-aEy2gbkTWhW9GAp8O1rrvn2owNwLiwrgA8XT8hTs61LyXCnEmzvuRHh_Ns2PT_ntqEAW5E_95e_dM0oUc6zRsj5x22U_rPGQ4HGtf7Tyu-6JFE1N21DovjiTrrIvJ8uTfnVfcBnBJFJwNZJw

###

// Test validation (INVALID ONE)
GET http://localhost:8080/api/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIwNzEyMzI5NDUsInJvbGUiOiJST0xFX0FETUlOIiwidXNlciI6ImFkbWluIn0.ukOiJTR7Xvv9o4RFYKTMTqicSjrpNikJ7zvX3vjZD8Aqy3Y2dgGO1L-J0Y2k9S5p9PmP-FZMB0ViU93bli2XA1A7sPUVoWYGMEyTw-k-zUWn_4jVR8LT3yx-d0wwVsbpx3zNBxtTKPYykshJ9sy1m950Hz20202j9ZnbBo2BRezq8sLpLFA_JhO9xLpAGtnTLdkFl-aEy2gbkTWhW9GAp8O1rrvn2owNwLiwrgA8XT8hTs61LyXCnEmzvuRHh_Ns2PT_ntqEAW5E_95e_dM0oUc6zRsj5x22U_rPGQ4HGtf7Tyu-6VfcBnBJFJwNZJw

###
